### ISSUE TITLE
roslaunch lab_slam run.launch 出现错误

### ISSUE THREAD

**Issue by HIT-Ygq** [TongxingJin/lab_slam#1]
cannot launch node of type [lab_slam/lab_slam]: Cannot locate node of type [lab_slam] in package [lab_slam].. Make sure file exists in package path and permission is set to executable (chmod +x)

**Comment by TongxingJin** [comment]
> cannot launch node of type [lab_slam/lab_slam]: Cannot locate node of type [lab_slam] in package [lab_slam].. Make sure file exists in package path and permission is set to executable (chmod +x)

It's fixed now, pls enjoy!
